### ISSUE TITLE
NPE in GameModel.processHit

### ISSUE THREAD

**Issue by VasilyKolpakov** [tepl/dudes#23]
`java.lang.NullPointerException
        at com.tearulez.dudes.GameModel.processHit(GameModel.java:229)
        at com.tearulez.dudes.GameModel.access$100(GameModel.java:12)
        at com.tearulez.dudes.GameModel$ListenerClass.beginContact(GameModel.java:251)
        at com.badlogic.gdx.physics.box2d.World.beginContact(World.java:985)
        at com.badlogic.gdx.physics.box2d.World.jniStep(Native Method)
        at com.badlogic.gdx.physics.box2d.World.step(World.java:689)
        at com.tearulez.dudes.GameModel.nextStep(GameModel.java:84)
        at com.tearulez.dudes.GameServer.lambda$startGameLoop$0(GameServer.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by VasilyKolpakov** [comment]
make regression test for this bug

**Comment by VasilyKolpakov** [comment]
blocked by #27

**Comment by VasilyKolpakov** [comment]
java.lang.NullPointerException
	at com.tearulez.dudes.model.GameModel.lambda$handlePlayerBulletCollisions$2(GameModel.java:101)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at com.tearulez.dudes.model.GameModel.handlePlayerBulletCollisions(GameModel.java:97)
	at com.tearulez.dudes.model.GameModel.nextStep(GameModel.java:90)
	at com.tearulez.dudes.server.GameServer.lambda$startGameLoop$0(GameServer.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
